package netif

import (
	"reflect"
	"testing"
)

// ★ 三个平台的 DNS 配置各用**真实输出**做样本。
//   解析这类东西，凭印象写的样本会恰好配合自己的误解 —— 之前邻居表就踩过一次。

func TestParseScutilDNS(t *testing.T) {
	// 真机 `scutil --dns` 的片段：第一个是全局 resolver（没有接口行），
	// 中间是 mDNS（有 domain/options，没有 nameserver），后面是按接口的 ——
	// ★ 注意接口名在 `if_index : 14 (en0)` 的**括号**里，而且排在 nameserver **后面**。
	const out = `DNS configuration

resolver #1
  nameserver[0] : 114.114.114.114
  nameserver[1] : 223.5.5.5
  flags    : Request A records
  reach    : 0x00000002 (Reachable)

resolver #2
  domain   : local
  options  : mdns
  timeout  : 5
  reach    : 0x00000000 (Not Reachable)
  order    : 300000

resolver #3
  nameserver[0] : fd00::1
  if_index : 13 (en7)
  flags    : Scoped, Request A records
  reach    : 0x00000002 (Reachable)

resolver #4
  nameserver[0] : 114.114.114.114
  if_index : 14 (en0)
  reach    : 0x00000002 (Reachable)
`
	got := parseScutilDNS(out)
	want := []DNSServer{
		{Addr: "114.114.114.114"},
		{Addr: "223.5.5.5"},
		{Addr: "fd00::1", Iface: "en7"},
	}
	// resolver #4 那台和 #1 重复 —— 去掉了：现场要的是「有哪几台」，不是「被配了几次」
	if !reflect.DeepEqual(got, want) {
		t.Errorf("想要 %+v\n拿到 %+v", want, got)
	}
}

func TestParseResolvConf(t *testing.T) {
	const text = `# generated by NetworkManager
search lan
nameserver 192.168.3.1
nameserver 8.8.8.8
options timeout:2 attempts:3
# nameserver 10.0.0.1
`
	got := parseResolvConf(text)
	want := []DNSServer{{Addr: "192.168.3.1"}, {Addr: "8.8.8.8"}}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("想要 %+v\n拿到 %+v", want, got)
	}
	// ★ systemd-resolved 的存根地址要**如实报**，不替它展开成真实上游：
	//   「本机其实在问 127.0.0.53」本身就是排查时最关键的一条信息
	stub := parseResolvConf("nameserver 127.0.0.53\noptions edns0 trust-ad\n")
	if len(stub) != 1 || stub[0].Addr != "127.0.0.53" {
		t.Errorf("存根地址该原样报出来，拿到 %+v", stub)
	}
}

func TestParseWinDNSServer(t *testing.T) {
	// 多个接口、每个接口多台服务器
	multi := `[{"InterfaceAlias":"Wi-Fi","ServerAddresses":["192.168.1.1","223.5.5.5"]},
	           {"InterfaceAlias":"以太网","ServerAddresses":["10.0.0.1"]}]`
	want := []DNSServer{
		{Addr: "192.168.1.1", Iface: "Wi-Fi"},
		{Addr: "223.5.5.5", Iface: "Wi-Fi"},
		{Addr: "10.0.0.1", Iface: "以太网"},
	}
	if got := parseWinDNSServer(multi); !reflect.DeepEqual(got, want) {
		t.Errorf("多接口：\n想要 %+v\n拿到 %+v", want, got)
	}

	// ★ 只有一个接口时 ConvertTo-Json 给的是**对象**不是数组 —— 只认数组的症状是
	//   「绝大多数机器读得到，单网卡机器读不到」，这种错最难复现
	one := `{"InterfaceAlias":"Wi-Fi","ServerAddresses":["192.168.1.1"]}`
	if got := parseWinDNSServer(one); !reflect.DeepEqual(got, []DNSServer{{Addr: "192.168.1.1", Iface: "Wi-Fi"}}) {
		t.Errorf("单接口：拿到 %+v", got)
	}

	// ★ ServerAddresses 只有一条时 PowerShell 也可能给字符串而不是数组
	str := `{"InterfaceAlias":"Wi-Fi","ServerAddresses":"192.168.1.1"}`
	if got := parseWinDNSServer(str); !reflect.DeepEqual(got, []DNSServer{{Addr: "192.168.1.1", Iface: "Wi-Fi"}}) {
		t.Errorf("地址是裸字符串：拿到 %+v", got)
	}

	for _, empty := range []string{"", "   ", "null", "not json"} {
		if got := parseWinDNSServer(empty); got != nil {
			t.Errorf("空输出 %q 该给 nil，拿到 %+v", empty, got)
		}
	}
}
